### ISSUE TITLE
Repo license

### ISSUE THREAD

**Issue by jasnow** [austinonrails/railsconf#7]
Can you please add a license to this repo so I can use it?
Thanks

Example: https://github.com/railstutorial/sample_app_rails_4/blob/master/LICENSE

Background Reference: http://opensource.org/licenses

**Comment by schneems** [comment]
I didn't write it. Can you give us a PR for an MIT license. And we can ping one of the contributors for merge.

**Comment by jasnow** [comment]
Requested PR: https://github.com/austinonrails/railsconf/pull/8

**Comment by damon** [comment]
2012, Damon Clinkscales, Chap Ambrose, Josh Butner

please go ahead and add those names and I'll merge it.

thx!

**Comment by jasnow** [comment]
@damon - Added years and authors.

**Comment by damon** [comment]
thanks
